dist: "trusty"
sudo: false
cache: pip

addons:
  apt:
    packages:
      - expect-dev  # provides unbuffer utility
      - python-lxml # because pip installation is slow
      - python3-dev # para que instale cups
      - libcups2-dev # para que instale cups

language: python

python:
  - "3.5"

env:
  global:
  - VERSION="12.0" TESTS="0" LINT_CHECK="0"

  matrix:
  - LINT_CHECK="1"
  - TESTS="1" ODOO_REPO="odoo/odoo"
  - TESTS="1" ODOO_REPO="OCA/OCB"

git:
  depth: 1

install:
  - pip install -r requirements.txt
  - git clone https://github.com/OCA/maintainer-quality-tools.git ${HOME}/maintainer-quality-tools
  - export PATH=${HOME}/maintainer-quality-tools/travis:${PATH}
  - pip install --upgrade python-magic
  - travis_install_nightly

script:
  - travis_run_tests

after_success:
  - travis_after_tests_success
